version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - asset_net
  web:
    image: letodev/asset_api
    build:
      context: ./API/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - NEW_RELIC_LICENSE_KEY=${KEY_NEW_RELIC}
    networks:
      - asset_net
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: letodev/mongo-asset-db
    build:
      context: ./DB/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - asset_net
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - asset_net
  agent:
    container_name: newrelic-infra
    build:
      context: ./newrelic-infra/
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
networks:
  asset_net:
    driver: bridge
