version: '3.8'

services:
  web:
    image: letodev/asset_api
    build:
      context: ./API/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - asset_net
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: letodev/mongo-asset-db
    build:
      context: ./DB/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - asset_net
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - asset_net
networks:
  asset_net:
    driver: bridge
