version: '3.8'

services:
  mongodb:
    image: letodev/mongo-asset-db
    build:
      context: ../DB/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - asset_net
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - asset_net
  agent:
    container_name: newrelic-infra
    build:
      context: ../newrelic-infra/
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
networks:
  asset_net:
    driver: bridge
